# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TRBsOKya4nOVFhcJkYBnTpnGce13VPTd
"""

import numpy as np
np.linspace(0,1,5)

np.linspace(0,20,8)

np.eye(3)

np.random.rand(3,2)

np.random.randn(3,2)

np.random.randint(1,5)

np.random.randint(34,100,30)

sample_array=np.arange(30)
sample_array

rand_array=np.random.randint(0,100,20)
rand_array

sample_array.reshape(3,10)

rand_array.min()

rand_array.argmin()

a=np.eye(5)
a

a.T

a=np.random.rand(2,3)
a

a.T

sample_array=np.arange(10,21)
sample_array

sample_array[3]

sample_array[1:7]

sample_array[0:7]

sample_array[1:4]=100
sample_array

sample_array[:]

sample_matrix=np.array([[1,12,13,15],[5,4,23,21],[7,8,55,47]])
sample_matrix

sample_matrix[2]

sample_matrix[2,:]

sample_matrix[:,(3,2)]

sample_matrix[0:2,2]

sample_array+sample_array

np.exp(sample_array)

np.sqrt(sample_array)

np.square(sample_array)

np.min(sample_array)

np.argmin(sample_array)

np.max(sample_array)

np.argmax(sample_array)

np.log(sample_array)

np.std(sample_array)

np.var(sample_array)

np.mean(sample_array)

array=np.random.randn(3,4)
array

np.round(array,decimals=3)

sports=np.array(['golf','cricket','fball','cricket','fball','basketball'])
sports

np.unique(sports)